version: 2
updates:
  - package-ecosystem: 'npm'
    directory: .
    schedule:
      interval: 'daily'
      time: '07:00'
      timezone: 'Europe/Amsterdam'
    open-pull-requests-limit: 10
    labels:
      - 'dependencies'
    ignore:
      - dependency-name: '@move4mobile*'
    groups:
      angular:
        applies-to: version-updates
        patterns:
          - '@angular*'
          - '@schematics/angular'
          - 'zone.js'
      nx:
        applies-to: version-updates
        patterns:
          - '@nx/*'
          - 'nx*'
      firebase:
        applies-to: version-updates
        patterns:
          - 'firebase'
          - 'firebase-*'
          - '@angular/fire'
          - '@firebase/*'
      firebase-admin:
        applies-to: version-updates
        patterns:
          - 'firebase-admin'
          - 'firebase-functions'
          - 'firebase-functions-test'
          - '@simondotm/nx-firebase'
      eslint:
        applies-to: version-updates
        patterns:
          - 'eslint*'
          - '@eslint/*'
          - 'eslint-config-*'
      typescript-eslint:
        applies-to: version-updates
        patterns:
          - '@typescript-eslint/*'
          - 'typescript-eslint'
      typescript:
        applies-to: version-updates
        patterns:
          - 'typescript'
          - 'tslib'
      swc:
        applies-to: version-updates
        patterns:
          - '@swc*'
      jest:
        applies-to: version-updates
        patterns:
          - 'jest'
          - 'jest-*'
          - '@jest/*'
          - 'ts-jest'
      tailwindcss:
        applies-to: version-updates
        patterns:
          - 'tailwindcss'
          - '@tailwindcss/*'
      types:
        applies-to: version-updates
        patterns:
          - '@types/*'

  - package-ecosystem: 'github-actions'
    directory: ''
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '07:00'
      timezone: 'Europe/Amsterdam'
    labels:
      - 'dependencies'
      - 'github-actions'
